### ISSUE TITLE
Feature: Update + marry various job postings + add links

### ISSUE THREAD

**Issue by thinkjrs** [musicfox/open-positions#5]
We need to update the posting within this issue to marry what we've posted elsewhere, as this is all public and we certainly need it to match. Down the road we'll improve this.

> By the way, the listings in the `current` directory are automagically scraped and deployed into our musicfox.io/team site.

Furthermore, we should probably give an edit to all of them, since they've been posted and had time to rest. I'll handle this one and ping @philipmuh when ready.

Lastly, we should add any external links to our job posting here, in the listing itself. 

## Requirements

- [x] Marry post content here with what we've posted externally @philipmuh 
- [x] Give a fresh look/edit to simplify and refine copy @thinkjrs 
- [x] Add external links on angel.co + linkedin (and others) to first posting in `current` directory @philipmuh 

@philipmuh For all of these open up a new branch when you edit and then a PR -- add me as the reviewer 👍

**Comment by philipmuh** [comment]
@thinkjrs I sorted on LinkedIn and AngelList
